## Example Docker Compose configuration
##
## Use this as a template to set up docker-compose, or as guide to set up other
## orchestration services

services:
  server:
    build: server
    volumes:
      - "${MOUNT_DATA}:/data"
      - "./server/config.toml:/opt/app/config.toml"
    ports:
      - 6666:6666
    stop_signal: SIGINT

  client:
    build: client
    depends_on:
      - server
    environment:
      BACKEND_HOST: server
      BASE_URL:
    volumes:
      - "${MOUNT_DATA}:/data:ro"
    ports:
      - "${PORT}:80"
