[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.38", features = ["full"] }
diesel = { version = "2.1", features = ["postgres", "time", "uuid"] }
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3", features = ["serde-human-readable"] }
uuid = { version = "1.8", features = ["v4", "serde"] }
argon2 = { version = "0.5", features = ["std"] }
rand_core = { version = "0.6", features = ["std"] }   # Necessary for argon2
pbkdf2 = { version = "0.12", features = ["simple"] }  # Necessary for argon2
toml = "0.8"
serde_json = "1.0"
base64 = "0.22"
warp = "0.3"
image = "0.25"
thiserror = "1.0"
itertools = "0.13"
once_cell = "1.19"
num-traits = "0.2"
num-derive = "0.4"