[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.38", features = ["full"] }
diesel = { version = "2.1", features = ["postgres", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
argon2 = { version = "0.5", features = ["std"] }
rand_core = { version = "0.6", features = ["std"] }   # Necessary for argon2
pbkdf2 = { version = "0.12", features = ["simple"] }  # Necessary for argon2
toml = "0.8"
warp = "0.3"
image = "0.25"
chrono = "0.4"
thiserror = "1.0"
once_cell = "1.19"
num-traits = "0.2"
num-derive = "0.4"